version: "3.9"

services:
  spring-petclinic:
    build: ./
    image: spring-petclinic:latest
    ports:
      - "8079:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
