FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app
COPY settings.xml /root/.m2/settings.xml

COPY pom.xml .

# previous layer cache
COPY src ./src

RUN mvn clean package -DskipTests -B

#run
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
